"""
Expand a Bmad lattice template set across instances.

Builds on :mod:`latform.apply` (single-file value/rename application) to render a
whole template set once per instance, rewriting ``call`` targets and Tao
``tao.init`` ``design_lattice`` paths to the generated files.
"""

from __future__ import annotations

import argparse
import pathlib
import posixpath
import re
from collections.abc import Mapping

from .apply import (
    _expand_ruleset_over_names,
    add_logging_argument,
    apply_renames,
    apply_values,
    configure_logging,
    delim_set,
    merge_rulesets,
    normalize_renames,
    split_namelist_key,
)
from .parser import MemoryFiles, parse
from .statements import Statement
from .tao import TaoInit, collect_tao_element_names, format_tao_namelist, rename_tao_elements
from .token import Role, Token
from .types import FormatOptions, NamelistFormatOptions
from .util import load_json_or_similar
from .walk import walk

__all__ = [
    "DEFAULT_HEADER",
    "instantiate",
    "load_instances",
    "write_instances",
    "main",
    "cli_main",
]


_INTERP = re.compile(r"\{instance(?::(upper|lower))?\}")

# Default comment header prepended to every generated file.
# Placeholders:
# * ``{source}`` (the file's template input path)
# * ``{instances}`` (the instances file)
# * ``{instance}`` (with ``:upper``/``:lower``).
DEFAULT_HEADER = "!** Generated by latform-template from {source} ({instances}); do not edit. **"


def _interpolate(text: str, instance: str) -> str:
    """Resolve ``{instance}``, ``{instance:upper}``, ``{instance:lower}``."""

    def repl(match: re.Match[str]) -> str:
        transform = match.group(1)
        if transform == "upper":
            return instance.upper()
        if transform == "lower":
            return instance.lower()
        return instance

    return _INTERP.sub(repl, text)


def _resolve_header(header: str, instance: str, source: str, instances_name: str) -> str:
    """
    Resolve a file's header text, ending in a blank line; ``""`` when opted out.
    """
    if not header:
        return ""
    text = header.replace("{source}", source).replace("{instances}", instances_name)
    return _interpolate(text, instance).rstrip("\n") + "\n\n"


def _interpolate_ruleset(rules: dict, instance: str) -> dict:
    return {
        "literal": {
            k: (orig, _interpolate(repl, instance)) for k, (orig, repl) in rules["literal"].items()
        },
        "regex": [(pat, _interpolate(repl, instance)) for pat, repl in rules["regex"]],
        "parts": [(d, frm, _interpolate(to, instance)) for d, frm, to in rules["parts"]],
    }


def _statement_text(statement: Statement, options: FormatOptions) -> str:
    from .output import format_statements

    return format_statements(statement, options)


def _apply_inserts(
    files: MemoryFiles, inserts: dict[str, list[dict[str, str]]], options: FormatOptions
) -> None:
    """
    Insert extra statements after an anchor in the named files.

    ``inserts`` maps a file basename to a list of ``{after, text}`` directives.
    """
    for basename, directives in inserts.items():
        path = _resolve_by_basename(files, basename)
        statements = list(files.by_filename[path])
        for directive in directives:
            anchor = directive["after"]
            new_statements = list(parse(directive["text"], "<insert>", annotate=False))
            index = _anchor_index(statements, anchor, options)
            statements[index + 1 : index + 1] = new_statements
        files.by_filename[path] = statements


def _anchor_index(statements: list[Statement], anchor: str, options: FormatOptions) -> int:
    for idx, statement in enumerate(statements):
        if anchor in _statement_text(statement, options):
            return idx
    raise KeyError(f"insert anchor not found: {anchor!r}")


def _resolve_by_basename(files: MemoryFiles, basename: str) -> pathlib.Path:
    for path in files.by_filename:
        if path.name == basename:
            return path
    raise KeyError(f"template has no file named {basename!r}")


def _relative_target(new_out: str, out_dir: str) -> str:
    """
    Make a mapped output path relative to the referencing file's output dir.

    Absolute and ``$VAR``-containing targets are kept verbatim — they do not
    live in the output tree, so relocating them would corrupt them.
    """
    if posixpath.isabs(new_out) or "$" in new_out:
        return new_out
    return posixpath.relpath(new_out, out_dir or ".")


def _map_reference(
    ref: str,
    in_dir: str,
    out_dir: str,
    explicit_paths: Mapping[str, str],
    in_to_out: Mapping[str, str],
) -> str | None:
    """
    Map one referenced path to its rewritten target, or None to leave it alone.

    Precedence:

    1. An explicit ``paths`` entry matching the reference resolved against the
       referencing file's input directory (template-root coordinates); the
       replacement is output-dir-relative and adjusted to ``out_dir``.
    2. An explicit ``paths`` entry matching the reference exactly as written;
       the replacement is inserted verbatim.
    3. The transform set's automatic input -> output mapping (adjusted to
       ``out_dir``).
    """
    resolved_in = posixpath.normpath(posixpath.join(in_dir, ref))
    new_out = explicit_paths.get(resolved_in)
    if new_out is not None:
        return _relative_target(new_out, out_dir)
    as_written = explicit_paths.get(posixpath.normpath(ref))
    if as_written is not None:
        return as_written
    new_out = in_to_out.get(resolved_in)
    if new_out is not None:
        return _relative_target(new_out, out_dir)
    return None


def _rewrite_call_filenames(
    files: MemoryFiles,
    transform_paths: Mapping[pathlib.Path, tuple[str, str]],
    in_to_out: Mapping[str, str],
    explicit_paths: Mapping[str, str],
) -> None:
    """
    Rewrite ``call`` targets (``call, file=`` and inline ``call::``) that
    resolve to a transform-set file or match an explicit ``paths`` entry.

    Parameters
    ----------
    transform_paths : Mapping[pathlib.Path, tuple[str, str]]
        ``{resolved_path: (input_rel, output_rel)}`` for the transform set.
    in_to_out : Mapping[str, str]
        Normalized input relative path -> output relative path for the
        transform set.
    explicit_paths : Mapping[str, str]
        Interpolated ``paths`` entries; see `_map_reference` for matching.
    """
    for path, (input_rel, output_rel) in transform_paths.items():
        in_dir = posixpath.dirname(input_rel)
        out_dir = posixpath.dirname(output_rel)
        for item in walk(files.by_filename[path]):
            node = item.node
            if not (isinstance(node, Token) and node.role is Role.filename):
                continue
            new_target = _map_reference(str(node), in_dir, out_dir, explicit_paths, in_to_out)
            if new_target is not None:
                item.replace(Token(new_target, role=Role.filename))


def _instantiate_tao_init(
    tao_init_spec: dict[str, str],
    override: dict | None,
    base_dir: pathlib.Path,
    in_to_out: Mapping[str, str],
    explicit_paths: Mapping[str, str],
    instance: str,
    options: NamelistFormatOptions | None = None,
    renames: dict[str, str] | None = None,
    rules: dict | None = None,
) -> dict[str, str]:
    """
    Render one instance's ``tao.init`` from the template spec.

    Rewrites ``design_lattice`` files to the instance's output lattice paths
    (via ``in_to_out``, the same map used for ``call`` targets), applies the
    instance's element renames to element references (via
    `latform.tao.rename_tao_elements`), and applies any per-instance namelist
    add/update overrides.

    ``renames`` is the literal map from the lattice rename (authoritative for
    names the lattices define). ``rules`` is the instance's interpolated
    ruleset; it is additionally expanded over the element names referenced in
    this file, so names only the ``tao.init`` knows (e.g. elements defined
    outside the template set) are renamed by the same rules.
    """
    input_rel = tao_init_spec["input"]
    output_rel = _interpolate(tao_init_spec["output"], instance)
    tao_init = TaoInit.from_file(base_dir / input_rel)

    in_dir = posixpath.dirname(input_rel)
    out_dir = posixpath.dirname(output_rel)
    remapped: list[str] = []
    changed = False
    for entry in tao_init.lattice_files:
        mapped = _map_reference(entry, in_dir, out_dir, explicit_paths, in_to_out)
        if mapped is None:
            remapped.append(entry)
        else:
            remapped.append(mapped)
            changed = True
    if changed:
        tao_init.lattice_files = remapped

    merged: dict[str, str] = {}
    if rules and (rules["literal"] or rules["regex"] or rules["parts"]):
        harvested = _expand_ruleset_over_names(rules, collect_tao_element_names(tao_init))
        merged.update({old.upper(): new for old, new in harvested.items()})
    # The lattice-expanded map wins on conflict (it is anchored to the names
    # the lattices actually define); keys are uppercased so differently-cased
    # references to the same element cannot shadow it.
    merged.update({old.upper(): new for old, new in (renames or {}).items()})
    if merged:
        rename_tao_elements(tao_init, merged)

    for name_key, assignments in ((override or {}).get("namelists") or {}).items():
        name, index = split_namelist_key(name_key)
        interpolated = {k: _interpolate(str(v), instance) for k, v in assignments.items()}
        tao_init.update_namelist(name, interpolated, index=index)

    return {output_rel: format_tao_namelist(tao_init, options=options)}


def _normalize_tao_init_specs(spec_value: dict | list[dict] | None) -> tuple[list[dict], bool]:
    """
    Normalize the spec-level ``tao_init`` to a list of ``{input, output}`` entries.

    Returns the entries plus whether the list form was used — per-instance
    overrides are keyed by ``input`` in the list form, and are the flat
    ``{namelists: ...}`` mapping in the single-mapping form.
    """
    if not spec_value:
        return [], False
    if isinstance(spec_value, list):
        inputs = [entry["input"] for entry in spec_value]
        duplicates = sorted({i for i in inputs if inputs.count(i) > 1})
        if duplicates:
            raise ValueError(f"duplicate tao_init input(s): {duplicates}")
        return list(spec_value), True
    return [spec_value], False


def _tao_init_override(
    overrides: dict,
    entry: dict[str, str],
    known_inputs: set[str],
    multi: bool,
) -> dict | None:
    """Resolve the per-instance ``tao_init`` override for one spec entry."""
    override = overrides.get("tao_init")
    if not override:
        return None
    if not multi:
        return override
    unknown = sorted(set(override) - known_inputs)
    if unknown:
        raise ValueError(
            f"per-instance tao_init override key(s) {unknown} do not match any "
            f"tao_init input: {sorted(known_inputs)}"
        )
    return override.get(entry["input"])


def load_instances(path: pathlib.Path | str) -> dict:
    """Load an instances YAML/etc file into a plain dict."""
    return load_json_or_similar(path)


def _spec_format_options(spec_format: dict | None, base: FormatOptions) -> FormatOptions:
    """
    Apply a spec-level ``format`` section onto ``base``.

    Keys are :class:`FormatOptions` field names (kebab- or snake-case), matching
    the ``[format]`` section of a latform config file. ``compact`` also flips
    ``newline_before_new_type`` (unless that is given explicitly), mirroring the
    ``latform`` CLI.
    """
    import dataclasses

    if not spec_format:
        return base

    kwargs = {str(key).replace("-", "_"): value for key, value in spec_format.items()}
    valid = {f.name for f in dataclasses.fields(FormatOptions)} - {"namelist", "renames"}
    unknown = sorted(set(kwargs) - valid)
    if unknown:
        raise ValueError(f"unknown format option(s) in instances file: {unknown}")
    if "compact" in kwargs and "newline_before_new_type" not in kwargs:
        kwargs["newline_before_new_type"] = not kwargs["compact"]
    return dataclasses.replace(base, **kwargs)


def instantiate(
    spec: dict,
    *,
    base_dir: pathlib.Path | str,
    options: FormatOptions | None = None,
    format_namelist: bool = True,
    instances_path: pathlib.Path | str | None = None,
) -> dict[str, dict[str, str]]:
    """
    Expand a template set across instances.

    Parameters
    ----------
    spec : dict
        Parsed instances file: ``template`` (list of ``{input, output}``),
        optional ``template_root`` (directory, relative to ``base_dir``, that
        all ``input``/``context`` paths are read from; the spec's path
        coordinates — inputs, ``paths`` keys, header ``{source}`` — remain
        relative to it), optional global ``renames``, optional ``paths`` (explicit path
        replacements for ``call``/``design_lattice`` targets:
        ``{referenced: replacement}``, interpolating ``{instance}``; a key
        matches the reference either resolved relative to the template root
        (replacement relative to the output dir) or exactly as written in the
        calling file (replacement inserted verbatim), and wins over the
        automatic transform-set rewrite; also usable per instance), optional
        ``delimiters`` (default delimiter
        set for prefix/suffix/parts), optional ``format`` (formatting options
        for the emitted files, config-file ``[format]`` style; applied on top
        of ``options``), optional ``tao_init`` (one ``{input, output}`` mapping
        or a list of them, for Tao ``tao.init`` files whose ``design_lattice``
        files are rewritten to the generated lattices), optional ``header``
        (comment text prepended to every generated file; `DEFAULT_HEADER` when
        absent, disabled when null/empty; interpolates ``{source}``,
        ``{instances}``, and ``{instance}``), and ``instances``
        (name -> overrides). A per-instance ``tao_init`` override adds or
        updates namelist sections via a ``namelists`` block
        (``{namelist: {key: value}}``, with a ``name#N`` suffix to target the
        N-th repeated group); with the list form, the override is keyed by the
        entry's ``input`` path (``{input: {namelists: ...}}``).
    base_dir : pathlib.Path | str
        Directory the ``input`` paths are relative to (the instances file's
        directory); a spec ``template_root`` is resolved against it.
    options : FormatOptions, optional
        Formatting options for emitted files.
    format_namelist : bool, optional
        Reformat the emitted ``tao.init`` namelist (field indentation and a
        blank line after each group) using ``options``. On by default; set False
        to preserve the template's namelist layout. Bmad lattice files are always
        reformatted regardless.
    instances_path : pathlib.Path | str, optional
        The instances file's path, used for the header's ``{instances}``
        placeholder (falls back to ``"instances.yaml"``).

    Returns
    -------
    dict[str, dict[str, str]]
        ``{instance_name: {output_basename: formatted_contents}}``.
    """
    from .output import default_options, format_statements

    base_dir = pathlib.Path(base_dir)
    options = _spec_format_options(spec.get("format"), options or default_options)
    header = spec.get("header", DEFAULT_HEADER) or ""
    instances_name = str(instances_path) if instances_path is not None else "instances.yaml"

    template_files = spec["template"]
    default_delims = delim_set(spec.get("delimiters"))
    global_rules = normalize_renames(spec.get("renames"), default_delims)
    global_paths = spec.get("paths") or {}
    instances = spec["instances"]
    context_files = spec.get("context") or []
    tao_init_specs, multi_tao_init = _normalize_tao_init_specs(spec.get("tao_init"))
    tao_init_inputs = {entry["input"] for entry in tao_init_specs}

    # All template inputs (template/context/tao_init) are read relative to
    # ``template_root``; the spec's own path coordinates are unaffected.
    input_dir = base_dir / spec["template_root"] if spec.get("template_root") else base_dir

    contents = {
        (input_dir / tf["input"]).resolve(): (input_dir / tf["input"]).read_text()
        for tf in template_files
    }
    input_basenames = {(input_dir / tf["input"]).resolve(): tf["input"] for tf in template_files}
    output_patterns = {(input_dir / tf["input"]).resolve(): tf["output"] for tf in template_files}

    # Resolution-only files: loaded so cross-file references resolve, but never
    # transformed or written, and calls to them are left untouched.
    context_contents = {
        (input_dir / c).resolve(): (input_dir / c).read_text() for c in context_files
    }

    results: dict[str, dict[str, str]] = {}
    for name, overrides in instances.items():
        overrides = overrides or {}
        # The whole set (transform + context) is loaded as top-level files, so
        # name resolution is complete across all of them at once.
        files = MemoryFiles.from_mapping({**contents, **context_contents})
        files.parse(recurse=False)
        files.annotate()

        if overrides.get("values"):
            apply_values(files, overrides["values"])
        if overrides.get("insert"):
            _apply_inserts(files, overrides["insert"], options)
        files.annotate()

        rules = merge_rulesets(
            global_rules, normalize_renames(overrides.get("renames"), default_delims)
        )
        # Replace {instance} and similar in the rename rules
        rules = _interpolate_ruleset(rules, name)
        element_renames: dict[str, str] = {}
        if rules["literal"] or rules["regex"] or rules["parts"]:
            element_renames = apply_renames(files, rules)

        # Full output path per input (may include directories). Rewrite `call`
        # targets by resolving each against the transform set's input paths.
        output_paths = {p: _interpolate(output_patterns[p], name) for p in contents}
        transform_paths = {p: (input_basenames[p], output_paths[p]) for p in contents}
        in_to_out = {posixpath.normpath(input_basenames[p]): output_paths[p] for p in contents}
        # Explicit path replacements (e.g. ../foo.bmad -> ../bar.bmad),
        # matched by resolved path or as written; they win over the automatic
        # transform-set rewrite (see _map_reference).
        explicit_paths = {
            posixpath.normpath(_interpolate(str(src), name)): _interpolate(str(dest), name)
            for src, dest in {**global_paths, **(overrides.get("paths") or {})}.items()
        }

        _rewrite_call_filenames(files, transform_paths, in_to_out, explicit_paths)

        instance_files = {
            output_paths[p]: (
                _resolve_header(header, name, input_basenames[p], instances_name)
                + format_statements(files.by_filename[p], options)
            )
            for p in contents
        }
        for entry in tao_init_specs:
            entry_header = _resolve_header(header, name, entry["input"], instances_name)
            rendered = _instantiate_tao_init(
                entry,
                _tao_init_override(overrides, entry, tao_init_inputs, multi_tao_init),
                input_dir,
                in_to_out,
                explicit_paths,
                name,
                options.namelist if format_namelist else None,
                renames=element_renames,
                rules=rules,
            )
            collisions = sorted(set(rendered) & set(instance_files))
            if collisions:
                raise ValueError(f"output path collision for instance {name!r}: {collisions}")
            instance_files.update({out: entry_header + text for out, text in rendered.items()})
        results[name] = instance_files

    return results


def write_instances(
    results: dict[str, dict[str, str]],
    output_dir: pathlib.Path | str,
) -> list[pathlib.Path]:
    """
    Write instantiated files to disk, creating parent directories as needed.

    Parameters
    ----------
    results : dict[str, dict[str, str]]
        The mapping returned by `instantiate`
        (``{instance: {output_path: contents}}``).
    output_dir : pathlib.Path | str
        Base directory; each output path is resolved relative to it.

    Returns
    -------
    list[pathlib.Path]
        The paths written.
    """
    output_dir = pathlib.Path(output_dir)
    written: list[pathlib.Path] = []
    for files in results.values():
        for rel_path, contents in files.items():
            path = output_dir / rel_path
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents)
            written.append(path)
    return written


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #

_INSTANTIATE_DESCRIPTION = """\
Expand a Bmad lattice template set across instances.

A YAML sidecar lists the template files and per-instance values, renames, and
output paths. See docs/cli.md.
"""


def _cmd_instantiate(parsed: argparse.Namespace) -> None:
    import dataclasses

    from . import cli
    from .output import default_options

    spec = load_json_or_similar(parsed.instances)
    base_dir = pathlib.Path(parsed.instances).resolve().parent
    options = dataclasses.replace(default_options, namelist=cli.build_namelist_options(parsed))
    results = instantiate(
        spec,
        base_dir=base_dir,
        options=options,
        format_namelist=parsed.format_namelist,
        instances_path=parsed.instances,
    )

    output_dir = pathlib.Path(parsed.output_dir)
    if parsed.dry_run:
        for files in results.values():
            for rel_path in files:
                print(f"would write: {output_dir / rel_path}")
        return

    for path in write_instances(results, output_dir):
        print(f"wrote: {path}")


def main(argv: list[str] | None = None) -> None:
    import sys

    parser = argparse.ArgumentParser(
        prog="latform-template",
        description=_INSTANTIATE_DESCRIPTION,
        formatter_class=argparse.RawTextHelpFormatter,
    )
    add_logging_argument(parser)
    parser.add_argument("instances", help="Instances YAML file")
    parser.add_argument(
        "-d",
        "--output-dir",
        default=".",
        help="Base directory for generated files (default: current directory)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Do not write files; list what would be written",
    )

    from . import cli

    cli.add_namelist_format_arguments(parser)

    parsed = parser.parse_args(argv if argv is not None else sys.argv[1:])
    configure_logging(parsed.log_level)
    _cmd_instantiate(parsed)


def cli_main(argv: list[str] | None = None) -> None:
    """CLI entrypoint for ``latform-template`` (instantiate a template set)."""
    main(argv)


if __name__ == "__main__":
    cli_main()
