"""
**Auto-generated; do not edit by hand.**

Tao ``*.init`` namelist type schema.
"""

from __future__ import annotations

from typing import NamedTuple


class Field(NamedTuple):
    """
    A namelist variable or struct member: kind, base type, shape, char length.

    * ``kind``   — ``"intrinsic"`` or ``"derived"``
    * ``base``   — the intrinsic type name (``character``/``integer``/``real``/
    ``logical``/``complex``) or, for derived fields, the lowercased struct name
    * ``array``  — ``None`` for a scalar, else ``(lbound, ubound)``; a ``None`` bound
    means unbounded/unknown (allocatable, symbolic, or multi-dimensional extent)
    * ``length`` — the declared ``character(N)`` length, or ``None`` for
    non-character fields and unknown/assumed lengths
    """

    kind: str
    base: str
    array: tuple[int | None, int | None] | None
    length: int | None = None


# Namelist name -> ``&tao_start`` key naming its optional separate file
# (``None`` = always read from tao.init).
FILE_KEY: dict[str, str | None] = {
    "tao_start": None,
    "tao_params": None,
    "tao_design_lattice": None,
    "tao_dynamic_aperture": None,
    "tao_beam_init": "beam_file",
    "tao_var": "var_file",
    "tao_d2_data": "data_file",
    "tao_d1_data": "data_file",
    "building_wall_orientation": "building_wall_file",
    "building_wall_section": "building_wall_file",
    "tao_plot_page": "plot_file",
    "tao_template_plot": "plot_file",
    "tao_template_graph": "plot_file",
    "floor_plan_drawing": "plot_file",
    "lat_layout_drawing": "plot_file",
    "element_shapes": "plot_file",
    "element_shapes_floor_plan": "plot_file",
    "element_shapes_lat_layout": "plot_file",
    "shape_pattern": "plot_file",
}

# Namelist name -> {variable name -> Field}.
NAMELISTS: dict[str, dict[str, Field]] = {
    "tao_start": {
        "startup_file": Field("intrinsic", "character", None, 200),
        "building_wall_file": Field("intrinsic", "character", None, 200),
        "hook_init_file": Field("intrinsic", "character", None, 200),
        "data_file": Field("intrinsic", "character", None, 200),
        "var_file": Field("intrinsic", "character", None, 200),
        "plot_file": Field("intrinsic", "character", None, 200),
        "beam_file": Field("intrinsic", "character", None, 200),
        "n_universes": Field("intrinsic", "integer", None),
        "init_name": Field("intrinsic", "character", None, 16),
    },
    "tao_params": {
        "global": Field("derived", "tao_global_struct", None),
        "bmad_com": Field("derived", "bmad_common_struct", None),
        "space_charge_com": Field("derived", "space_charge_common_struct", None),
        "opti_de_param": Field("derived", "opti_de_param_struct", None),
        "n_data_max": Field("intrinsic", "integer", None),
        "n_var_max": Field("intrinsic", "integer", None),
        "n_d2_data_max": Field("intrinsic", "integer", None),
        "n_v1_var_max": Field("intrinsic", "integer", None),
    },
    "tao_design_lattice": {
        "design_lattice": Field("derived", "tao_design_lat_input", (1, 200)),
        "combine_consecutive_elements_of_like_name": Field("intrinsic", "logical", None),
        "unique_name_suffix": Field("intrinsic", "character", None, 100),
        "n_universes": Field("intrinsic", "integer", None),
    },
    "tao_dynamic_aperture": {
        "ix_universe": Field("intrinsic", "integer", None),
        "da_param": Field("derived", "aperture_param_struct", None),
        "pz": Field("intrinsic", "real", (1, 100)),
        "a_emit": Field("intrinsic", "real", None),
        "b_emit": Field("intrinsic", "real", None),
        "ellipse_scale": Field("intrinsic", "real", None),
    },
    "tao_beam_init": {
        "ix_universe": Field("intrinsic", "integer", None),
        "beam_init": Field("derived", "beam_init_struct", None),
        "always_reinit": Field("intrinsic", "logical", None),
        "beam0_file": Field("intrinsic", "character", None, 200),
        "beam_init_file_name": Field("intrinsic", "character", None, 200),
        "beam_position0_file": Field("intrinsic", "character", None, 200),
        "beam_track_start": Field("intrinsic", "character", None, 40),
        "beam_track_end": Field("intrinsic", "character", None, 40),
        "beam_saved_at": Field("intrinsic", "character", None, 200),
        "beam_dump_at": Field("intrinsic", "character", None, 200),
        "beam_dump_file": Field("intrinsic", "character", None, 200),
        "track_start": Field("intrinsic", "character", None, 40),
        "track_end": Field("intrinsic", "character", None, 40),
        "saved_at": Field("intrinsic", "character", None, 200),
        "dump_at": Field("intrinsic", "character", None, 200),
        "dump_file": Field("intrinsic", "character", None, 200),
        "comb_ds_save": Field("intrinsic", "real", None),
    },
    "tao_var": {
        "v1_var": Field("derived", "tao_v1_var_input", None),
        "var": Field("derived", "tao_var_input", (-100, 5000)),
        "default_weight": Field("intrinsic", "real", None),
        "default_meas": Field("intrinsic", "real", None),
        "default_step": Field("intrinsic", "real", None),
        "default_key_delta": Field("intrinsic", "real", None),
        "ix_min_var": Field("intrinsic", "integer", None),
        "ix_max_var": Field("intrinsic", "integer", None),
        "default_universe": Field("intrinsic", "character", None, 40),
        "default_attribute": Field("intrinsic", "character", None, 40),
        "default_low_lim": Field("intrinsic", "real", None),
        "default_high_lim": Field("intrinsic", "real", None),
        "default_merit_type": Field("intrinsic", "character", None, 40),
        "default_good_user": Field("intrinsic", "logical", None),
        "use_same_lat_eles_as": Field("intrinsic", "character", None, 40),
        "search_for_lat_eles": Field("intrinsic", "character", None, 200),
        "default_key_bound": Field("intrinsic", "logical", None),
    },
    "tao_d2_data": {
        "d2_data": Field("derived", "tao_d2_data_input", None),
        "n_d1_data": Field("intrinsic", "integer", None),
        "universe": Field("intrinsic", "character", None, 40),
        "default_merit_type": Field("intrinsic", "character", None, 40),
        "default_weight": Field("intrinsic", "real", None),
        "default_meas": Field("intrinsic", "real", None),
        "default_data_type": Field("intrinsic", "character", None, 200),
        "default_data_source": Field("intrinsic", "character", None, 40),
    },
    "tao_d1_data": {
        "d1_data": Field("derived", "tao_d1_data_input", None),
        "datum": Field("derived", "tao_datum_input", (1, None)),
        "ix_d1_data": Field("intrinsic", "integer", None),
        "default_merit_type": Field("intrinsic", "character", None, 40),
        "default_weight": Field("intrinsic", "real", None),
        "default_meas": Field("intrinsic", "real", None),
        "default_data_type": Field("intrinsic", "character", None, 200),
        "default_data_source": Field("intrinsic", "character", None, 40),
        "use_same_lat_eles_as": Field("intrinsic", "character", None, 40),
        "search_for_lat_eles": Field("intrinsic", "character", None, 200),
        "ix_min_data": Field("intrinsic", "integer", None),
        "ix_max_data": Field("intrinsic", "integer", None),
    },
    "building_wall_orientation": {
        "theta": Field("intrinsic", "real", None),
        "x_offset": Field("intrinsic", "real", None),
        "z_offset": Field("intrinsic", "real", None),
    },
    "building_wall_section": {
        "constraint": Field("intrinsic", "character", None, 16),
        "name": Field("intrinsic", "character", None, 40),
        "point": Field("derived", "tao_building_wall_point_struct", (1, 100)),
    },
    "tao_plot_page": {
        "plot_page": Field("derived", "tao_plot_page_input", None),
        "default_plot": Field("derived", "tao_plot_input", None),
        "default_graph": Field("derived", "tao_graph_input", None),
        "region": Field("derived", "tao_region_input", (1, 100)),
        "place": Field("derived", "tao_place_input", (1, 30)),
        "include_default_plots": Field("intrinsic", "logical", None),
    },
    "tao_template_plot": {
        "plot": Field("derived", "tao_plot_input", None),
        "default_graph": Field("derived", "tao_graph_input", None),
        "default_curve": Field("derived", "tao_curve_input", None),
    },
    "tao_template_graph": {
        "graph": Field("derived", "tao_graph_input", None),
        "graph_index": Field("intrinsic", "integer", None),
        "curve": Field("derived", "tao_curve_input", (1, 40)),
    },
    "floor_plan_drawing": {
        "ele_shape": Field("derived", "tao_ele_shape_input", (1, 60)),
        "include_default_shapes": Field("intrinsic", "logical", None),
    },
    "lat_layout_drawing": {
        "ele_shape": Field("derived", "tao_ele_shape_input", (1, 60)),
        "include_default_shapes": Field("intrinsic", "logical", None),
    },
    "element_shapes": {
        "shape": Field("derived", "old_tao_ele_shape_struct", (1, 30)),
    },
    "element_shapes_floor_plan": {
        "ele_shape": Field("derived", "tao_ele_shape_input", (1, 60)),
    },
    "element_shapes_lat_layout": {
        "ele_shape": Field("derived", "tao_ele_shape_input", (1, 60)),
    },
    "shape_pattern": {
        "name": Field("intrinsic", "character", None, 40),
        "line": Field("derived", "qp_line_struct", None),
        "pt": Field("derived", "tao_shape_pattern_point_struct", (1, 30)),
        "scale": Field("intrinsic", "character", None, 8),
    },
}

# Derived struct name -> {member name -> Field} (reachable closure only).
STRUCTS: dict[str, dict[str, Field]] = {
    "tao_shape_pattern_point_struct": {
        "s": Field("intrinsic", "real", None),
        "y": Field("intrinsic", "real", None),
        "radius": Field("intrinsic", "real", None),
    },
    "qp_line_struct": {
        "width": Field("intrinsic", "integer", None),
        "color": Field("intrinsic", "character", None, 24),
        "pattern": Field("intrinsic", "character", None, 16),
    },
    "tao_ele_shape_input": {
        "ele_id": Field("intrinsic", "character", None, 60),
        "shape": Field("intrinsic", "character", None, 40),
        "color": Field("intrinsic", "character", None, 24),
        "size": Field("intrinsic", "real", None),
        "label": Field("intrinsic", "character", None, 16),
        "draw": Field("intrinsic", "logical", None),
        "multi": Field("intrinsic", "logical", None),
        "line_width": Field("intrinsic", "integer", None),
        "offset": Field("intrinsic", "real", None),
    },
    "tao_curve_input": {
        "name": Field("intrinsic", "character", None, 40),
        "data_source": Field("intrinsic", "character", None, 40),
        "data_type_x": Field("intrinsic", "character", None, 100),
        "data_type_z": Field("intrinsic", "character", None, 100),
        "data_type": Field("intrinsic", "character", None, 200),
        "data_index": Field("intrinsic", "character", None, 100),
        "legend_text": Field("intrinsic", "character", None, 40),
        "units": Field("intrinsic", "character", None, 40),
        "component": Field("intrinsic", "character", None, 60),
        "y_axis_scale_factor": Field("intrinsic", "real", None),
        "z_color0": Field("intrinsic", "real", None),
        "z_color1": Field("intrinsic", "real", None),
        "symbol_every": Field("intrinsic", "integer", None),
        "ix_universe": Field("intrinsic", "integer", None),
        "n_turn": Field("intrinsic", "integer", None),
        "draw_line": Field("intrinsic", "logical", None),
        "draw_symbols": Field("intrinsic", "logical", None),
        "draw_symbol_index": Field("intrinsic", "logical", None),
        "draw_error_bars": Field("intrinsic", "logical", None),
        "use_y2": Field("intrinsic", "logical", None),
        "use_z_color": Field("intrinsic", "logical", None),
        "autoscale_z_color": Field("intrinsic", "logical", None),
        "smooth_line_calc": Field("intrinsic", "logical", None),
        "ele_ref_name": Field("intrinsic", "character", None, 40),
        "ix_branch": Field("intrinsic", "integer", None),
        "ix_bunch": Field("intrinsic", "integer", None),
        "line": Field("derived", "qp_line_struct", None),
        "symbol": Field("derived", "qp_symbol_struct", None),
        "hist": Field("derived", "tao_histogram_struct", None),
        "orbit": Field("derived", "tao_curve_orbit_struct", None),
        "z_color": Field("derived", "tao_curve_color_struct", None),
    },
    "tao_curve_color_struct": {
        "data_type": Field("intrinsic", "character", None, 100),
        "is_on": Field("intrinsic", "logical", None),
        "min": Field("intrinsic", "real", None),
        "max": Field("intrinsic", "real", None),
        "autoscale": Field("intrinsic", "logical", None),
    },
    "tao_curve_orbit_struct": {
        "x": Field("intrinsic", "real", None),
        "y": Field("intrinsic", "real", None),
        "t": Field("intrinsic", "real", None),
    },
    "tao_histogram_struct": {
        "density_normalized": Field("intrinsic", "logical", None),
        "weight_by_charge": Field("intrinsic", "logical", None),
        "minimum": Field("intrinsic", "real", None),
        "maximum": Field("intrinsic", "real", None),
        "width": Field("intrinsic", "real", None),
        "center": Field("intrinsic", "real", None),
        "number": Field("intrinsic", "integer", None),
    },
    "qp_symbol_struct": {
        "type": Field("intrinsic", "character", None, 16),
        "height": Field("intrinsic", "real", None),
        "color": Field("intrinsic", "character", None, 24),
        "fill_pattern": Field("intrinsic", "character", None, 16),
        "line_width": Field("intrinsic", "integer", None),
    },
    "tao_graph_input": {
        "name": Field("intrinsic", "character", None, 40),
        "type": Field("intrinsic", "character", None, 40),
        "title": Field("intrinsic", "character", None, 80),
        "component": Field("intrinsic", "character", None, 60),
        "text_legend": Field("intrinsic", "character", (1, 10), 100),
        "floor_plan_view": Field("intrinsic", "character", None, 2),
        "floor_plan_orbit_color": Field("intrinsic", "character", None, 24),
        "box": Field("intrinsic", "integer", (1, 4)),
        "ix_universe": Field("intrinsic", "integer", None),
        "ix_branch": Field("intrinsic", "integer", None),
        "n_curve": Field("intrinsic", "integer", None),
        "x_axis_scale_factor": Field("intrinsic", "real", None),
        "symbol_size_scale": Field("intrinsic", "real", None),
        "floor_plan_rotation": Field("intrinsic", "real", None),
        "floor_plan_orbit_scale": Field("intrinsic", "real", None),
        "floor_plan_flip_label_side": Field("intrinsic", "logical", None),
        "floor_plan_size_is_absolute": Field("intrinsic", "logical", None),
        "floor_plan_draw_only_first_pass": Field("intrinsic", "logical", None),
        "correct_xy_distortion": Field("intrinsic", "logical", None),
        "clip": Field("intrinsic", "logical", None),
        "draw_title": Field("intrinsic", "logical", None),
        "draw_axes": Field("intrinsic", "logical", None),
        "draw_grid": Field("intrinsic", "logical", None),
        "draw_curve_legend": Field("intrinsic", "logical", None),
        "draw_only_good_user_data_or_vars": Field("intrinsic", "logical", None),
        "allow_wrap_around": Field("intrinsic", "logical", None),
        "floor_plan": Field("derived", "tao_floor_plan_struct", None),
        "text_legend_origin": Field("derived", "qp_point_struct", None),
        "curve_legend_origin": Field("derived", "qp_point_struct", None),
        "margin": Field("derived", "qp_rect_struct", None),
        "scale_margin": Field("derived", "qp_rect_struct", None),
        "x": Field("derived", "qp_axis_struct", None),
        "y": Field("derived", "qp_axis_struct", None),
        "x2": Field("derived", "qp_axis_struct", None),
        "y2": Field("derived", "qp_axis_struct", None),
        "curve_legend": Field("derived", "qp_legend_struct", None),
    },
    "qp_legend_struct": {
        "row_spacing": Field("intrinsic", "real", None),
        "line_length": Field("intrinsic", "real", None),
        "text_offset": Field("intrinsic", "real", None),
        "draw_line": Field("intrinsic", "logical", None),
        "draw_symbol": Field("intrinsic", "logical", None),
        "draw_text": Field("intrinsic", "logical", None),
    },
    "qp_axis_struct": {
        "label": Field("intrinsic", "character", None, 80),
        "min": Field("intrinsic", "real", None),
        "max": Field("intrinsic", "real", None),
        "tick_min": Field("intrinsic", "real", None),
        "tick_max": Field("intrinsic", "real", None),
        "eval_min": Field("intrinsic", "real", None),
        "eval_max": Field("intrinsic", "real", None),
        "dtick": Field("intrinsic", "real", None),
        "number_offset": Field("intrinsic", "real", None),
        "label_offset": Field("intrinsic", "real", None),
        "major_tick_len": Field("intrinsic", "real", None),
        "minor_tick_len": Field("intrinsic", "real", None),
        "label_color": Field("intrinsic", "character", None, 24),
        "major_div": Field("intrinsic", "integer", None),
        "major_div_nominal": Field("intrinsic", "integer", None),
        "minor_div": Field("intrinsic", "integer", None),
        "minor_div_max": Field("intrinsic", "integer", None),
        "places": Field("intrinsic", "integer", None),
        "type": Field("intrinsic", "character", None, 16),
        "bounds": Field("intrinsic", "character", None, 16),
        "tick_side": Field("intrinsic", "integer", None),
        "number_side": Field("intrinsic", "integer", None),
        "draw_label": Field("intrinsic", "logical", None),
        "draw_numbers": Field("intrinsic", "logical", None),
    },
    "qp_rect_struct": {
        "x1": Field("intrinsic", "real", None),
        "x2": Field("intrinsic", "real", None),
        "y1": Field("intrinsic", "real", None),
        "y2": Field("intrinsic", "real", None),
        "units": Field("intrinsic", "character", None, 16),
    },
    "qp_point_struct": {
        "x": Field("intrinsic", "real", None),
        "y": Field("intrinsic", "real", None),
        "units": Field("intrinsic", "character", None, 16),
    },
    "tao_floor_plan_struct": {
        "view": Field("intrinsic", "character", None, 2),
        "rotation": Field("intrinsic", "real", None),
        "correct_distortion": Field("intrinsic", "logical", None),
        "flip_label_side": Field("intrinsic", "logical", None),
        "size_is_absolute": Field("intrinsic", "logical", None),
        "draw_only_first_pass": Field("intrinsic", "logical", None),
        "draw_building_wall": Field("intrinsic", "logical", None),
        "orbit_scale": Field("intrinsic", "real", None),
        "orbit_color": Field("intrinsic", "character", None, 24),
        "orbit_pattern": Field("intrinsic", "character", None, 16),
        "orbit_lattice": Field("intrinsic", "character", None, 16),
        "orbit_width": Field("intrinsic", "integer", None),
    },
    "tao_plot_input": {
        "name": Field("intrinsic", "character", None, 40),
        "description": Field("intrinsic", "character", None, 60),
        "x_axis_type": Field("intrinsic", "character", None, 16),
        "n_graph": Field("intrinsic", "integer", None),
        "autoscale_gang_x": Field("intrinsic", "logical", None),
        "autoscale_gang_y": Field("intrinsic", "logical", None),
        "autoscale_x": Field("intrinsic", "logical", None),
        "autoscale_y": Field("intrinsic", "logical", None),
        "n_curve_pts": Field("intrinsic", "integer", None),
        "x": Field("derived", "qp_axis_struct", None),
    },
    "tao_place_input": {
        "region": Field("intrinsic", "character", None, 40),
        "plot": Field("intrinsic", "character", None, 40),
    },
    "tao_region_input": {
        "name": Field("intrinsic", "character", None, 40),
        "location": Field("intrinsic", "real", (1, 4)),
    },
    "tao_plot_page_input": {
        "title": Field("derived", "tao_title_struct", None),
        "subtitle": Field("derived", "tao_title_struct", None),
        "border": Field("derived", "qp_rect_struct", None),
        "plot_display_type": Field("intrinsic", "character", None, 8),
        "size": Field("intrinsic", "real", (1, 2)),
        "text_height": Field("intrinsic", "real", None),
        "main_title_text_scale": Field("intrinsic", "real", None),
        "graph_title_text_scale": Field("intrinsic", "real", None),
        "axis_number_text_scale": Field("intrinsic", "real", None),
        "axis_label_text_scale": Field("intrinsic", "real", None),
        "legend_text_scale": Field("intrinsic", "real", None),
        "key_table_text_scale": Field("intrinsic", "real", None),
        "floor_plan_shape_scale": Field("intrinsic", "real", None),
        "floor_plan_text_scale": Field("intrinsic", "real", None),
        "lat_layout_shape_scale": Field("intrinsic", "real", None),
        "lat_layout_text_scale": Field("intrinsic", "real", None),
        "curve_legend_line_len": Field("intrinsic", "real", None),
        "curve_legend_text_offset": Field("intrinsic", "real", None),
        "n_curve_pts": Field("intrinsic", "integer", None),
        "delete_overlapping_plots": Field("intrinsic", "logical", None),
        "draw_graph_title_suffix": Field("intrinsic", "logical", None),
    },
    "tao_title_struct": {
        "string": Field("intrinsic", "character", None, 100),
        "x": Field("intrinsic", "real", None),
        "y": Field("intrinsic", "real", None),
        "units": Field("intrinsic", "character", None, 16),
        "justify": Field("intrinsic", "character", None, 2),
        "draw_it": Field("intrinsic", "logical", None),
    },
    "tao_building_wall_point_struct": {
        "z": Field("intrinsic", "real", None),
        "x": Field("intrinsic", "real", None),
        "radius": Field("intrinsic", "real", None),
        "z_center": Field("intrinsic", "real", None),
        "x_center": Field("intrinsic", "real", None),
    },
    "tao_datum_input": {
        "data_type": Field("intrinsic", "character", None, 600),
        "ele_ref_name": Field("intrinsic", "character", None, 40),
        "ele_start_name": Field("intrinsic", "character", None, 40),
        "ele_name": Field("intrinsic", "character", None, 40),
        "merit_type": Field("intrinsic", "character", None, 20),
        "meas": Field("intrinsic", "real", None),
        "weight": Field("intrinsic", "real", None),
        "good_user": Field("intrinsic", "logical", None),
        "good_opt": Field("intrinsic", "logical", None),
        "data_source": Field("intrinsic", "character", None, 20),
        "eval_point": Field("intrinsic", "character", None, 20),
        "s_offset": Field("intrinsic", "real", None),
        "ref_s_offset": Field("intrinsic", "real", None),
        "ix_bunch": Field("intrinsic", "integer", None),
        "spin_axis": Field("derived", "spin_axis_struct", None),
        "invalid_value": Field("intrinsic", "real", None),
        "error_rms": Field("intrinsic", "real", None),
    },
    "spin_axis_struct": {
        "l": Field("intrinsic", "real", (1, 3)),
        "n0": Field("intrinsic", "real", (1, 3)),
        "m": Field("intrinsic", "real", (1, 3)),
    },
    "tao_d1_data_input": {
        "name": Field("intrinsic", "character", None, 40),
    },
    "tao_d2_data_input": {
        "name": Field("intrinsic", "character", None, 40),
    },
    "tao_var_input": {
        "ele_name": Field("intrinsic", "character", None, 40),
        "attribute": Field("intrinsic", "character", None, 40),
        "universe": Field("intrinsic", "character", None, 16),
        "weight": Field("intrinsic", "real", None),
        "step": Field("intrinsic", "real", None),
        "low_lim": Field("intrinsic", "real", None),
        "high_lim": Field("intrinsic", "real", None),
        "merit_type": Field("intrinsic", "character", None, 40),
        "good_user": Field("intrinsic", "logical", None),
        "key_bound": Field("intrinsic", "logical", None),
        "key_delta": Field("intrinsic", "real", None),
        "meas": Field("intrinsic", "real", None),
    },
    "tao_v1_var_input": {
        "name": Field("intrinsic", "character", None, 40),
    },
    "beam_init_struct": {
        "position_file": Field("intrinsic", "character", None, 400),
        "distribution_type": Field("intrinsic", "character", (1, 3), 16),
        "spin": Field("intrinsic", "real", (1, 3)),
        "ellipse": Field("derived", "ellipse_beam_init_struct", (1, 3)),
        "kv": Field("derived", "kv_beam_init_struct", None),
        "grid": Field("derived", "grid_beam_init_struct", (1, 3)),
        "center_jitter": Field("intrinsic", "real", (1, 6)),
        "emit_jitter": Field("intrinsic", "real", (1, 2)),
        "sig_z_jitter": Field("intrinsic", "real", None),
        "sig_pz_jitter": Field("intrinsic", "real", None),
        "n_particle": Field("intrinsic", "integer", None),
        "renorm_center": Field("intrinsic", "logical", None),
        "renorm_sigma": Field("intrinsic", "logical", None),
        "random_engine": Field("intrinsic", "character", None, 16),
        "random_gauss_converter": Field("intrinsic", "character", None, 16),
        "random_sigma_cutoff": Field("intrinsic", "real", None),
        "a_norm_emit": Field("intrinsic", "real", None),
        "b_norm_emit": Field("intrinsic", "real", None),
        "a_emit": Field("intrinsic", "real", None),
        "b_emit": Field("intrinsic", "real", None),
        "dpz_dz": Field("intrinsic", "real", None),
        "center": Field("intrinsic", "real", (1, 6)),
        "t_offset": Field("intrinsic", "real", None),
        "dt_bunch": Field("intrinsic", "real", None),
        "sig_z": Field("intrinsic", "real", None),
        "sig_pz": Field("intrinsic", "real", None),
        "bunch_charge": Field("intrinsic", "real", None),
        "n_bunch": Field("intrinsic", "integer", None),
        "ix_turn": Field("intrinsic", "integer", None),
        "species": Field("intrinsic", "character", None, 16),
        "full_6d_coupling_calc": Field("intrinsic", "logical", None),
        "use_particle_start": Field("intrinsic", "logical", None),
        "use_t_coords": Field("intrinsic", "logical", None),
        "use_z_as_t": Field("intrinsic", "logical", None),
        "file_name": Field("intrinsic", "character", None, 200),
    },
    "grid_beam_init_struct": {
        "n_x": Field("intrinsic", "integer", None),
        "n_px": Field("intrinsic", "integer", None),
        "x_min": Field("intrinsic", "real", None),
        "x_max": Field("intrinsic", "real", None),
        "px_min": Field("intrinsic", "real", None),
        "px_max": Field("intrinsic", "real", None),
    },
    "kv_beam_init_struct": {
        "part_per_phi": Field("intrinsic", "integer", (1, 2)),
        "n_i2": Field("intrinsic", "integer", None),
        "a": Field("intrinsic", "real", None),
    },
    "ellipse_beam_init_struct": {
        "part_per_ellipse": Field("intrinsic", "integer", None),
        "n_ellipse": Field("intrinsic", "integer", None),
        "sigma_cutoff": Field("intrinsic", "real", None),
    },
    "aperture_param_struct": {
        "min_angle": Field("intrinsic", "real", None),
        "max_angle": Field("intrinsic", "real", None),
        "n_angle": Field("intrinsic", "integer", None),
        "n_turn": Field("intrinsic", "integer", None),
        "x_init": Field("intrinsic", "real", None),
        "y_init": Field("intrinsic", "real", None),
        "rel_accuracy": Field("intrinsic", "real", None),
        "abs_accuracy": Field("intrinsic", "real", None),
        "start_ele": Field("intrinsic", "character", None, 40),
    },
    "tao_design_lat_input": {
        "file": Field("intrinsic", "character", None, 400),
        "file2": Field("intrinsic", "character", None, 400),
        "language": Field("intrinsic", "character", None, 16),
        "use_line": Field("intrinsic", "character", None, 40),
        "one_turn_map_calc": Field("intrinsic", "logical", None),
        "dynamic_aperture_calc": Field("intrinsic", "logical", None),
        "reverse_lattice": Field("intrinsic", "logical", None),
        "start_branch_at": Field("intrinsic", "character", None, 40),
        "slice_lattice": Field("intrinsic", "character", None, 80),
        "use_element_range": Field("intrinsic", "character", (1, 2), 40),
    },
    "opti_de_param_struct": {
        "cr": Field("intrinsic", "real", None),
        "f": Field("intrinsic", "real", None),
        "l_best": Field("intrinsic", "real", None),
        "use_2nd_diff": Field("intrinsic", "logical", None),
        "binomial_cross": Field("intrinsic", "logical", None),
        "randomize_f": Field("intrinsic", "logical", None),
        "minimize_merit": Field("intrinsic", "logical", None),
    },
    "space_charge_common_struct": {
        "ds_track_step": Field("intrinsic", "real", None),
        "dt_track_step": Field("intrinsic", "real", None),
        "cathode_strength_cutoff": Field("intrinsic", "real", None),
        "rel_tol_tracking": Field("intrinsic", "real", None),
        "abs_tol_tracking": Field("intrinsic", "real", None),
        "beam_chamber_height": Field("intrinsic", "real", None),
        "lsc_sigma_cutoff": Field("intrinsic", "real", None),
        "particle_sigma_cutoff": Field("intrinsic", "real", None),
        "mesh_growth_factor": Field("intrinsic", "real", None),
        "mesh_shrink_factor": Field("intrinsic", "real", None),
        "space_charge_mesh_size": Field("intrinsic", "integer", (1, 3)),
        "csr3d_mesh_size": Field("intrinsic", "integer", (1, 3)),
        "n_bin": Field("intrinsic", "integer", None),
        "particle_bin_span": Field("intrinsic", "integer", None),
        "n_shield_images": Field("intrinsic", "integer", None),
        "sc_min_in_bin": Field("intrinsic", "integer", None),
        "lsc_kick_transverse_dependence": Field("intrinsic", "logical", None),
        "debug": Field("intrinsic", "logical", None),
        "diagnostic_output_file": Field("intrinsic", "character", None, 400),
    },
    "bmad_common_struct": {
        "max_aperture_limit": Field("intrinsic", "real", None),
        "d_orb": Field("intrinsic", "real", (1, 6)),
        "default_ds_step": Field("intrinsic", "real", None),
        "significant_length": Field("intrinsic", "real", None),
        "rel_tol_tracking": Field("intrinsic", "real", None),
        "abs_tol_tracking": Field("intrinsic", "real", None),
        "rel_tol_adaptive_tracking": Field("intrinsic", "real", None),
        "abs_tol_adaptive_tracking": Field("intrinsic", "real", None),
        "init_ds_adaptive_tracking": Field("intrinsic", "real", None),
        "min_ds_adaptive_tracking": Field("intrinsic", "real", None),
        "fatal_ds_adaptive_tracking": Field("intrinsic", "real", None),
        "autoscale_amp_abs_tol": Field("intrinsic", "real", None),
        "autoscale_amp_rel_tol": Field("intrinsic", "real", None),
        "autoscale_phase_tol": Field("intrinsic", "real", None),
        "electric_dipole_moment": Field("intrinsic", "real", None),
        "synch_rad_scale": Field("intrinsic", "real", None),
        "sad_eps_scale": Field("intrinsic", "real", None),
        "sad_amp_max": Field("intrinsic", "real", None),
        "sad_n_div_max": Field("intrinsic", "integer", None),
        "taylor_order": Field("intrinsic", "integer", None),
        "runge_kutta_order": Field("intrinsic", "integer", None),
        "default_integ_order": Field("intrinsic", "integer", None),
        "max_num_runge_kutta_step": Field("intrinsic", "integer", None),
        "rf_phase_below_transition_ref": Field("intrinsic", "logical", None),
        "sr_wakes_on": Field("intrinsic", "logical", None),
        "lr_wakes_on": Field("intrinsic", "logical", None),
        "auto_bookkeeper": Field("intrinsic", "logical", None),
        "high_energy_space_charge_on": Field("intrinsic", "logical", None),
        "high_energy_space_charge_linear": Field("intrinsic", "logical", None),
        "csr_and_space_charge_on": Field("intrinsic", "logical", None),
        "spin_tracking_on": Field("intrinsic", "logical", None),
        "spin_sokolov_ternov_flipping_on": Field("intrinsic", "logical", None),
        "radiation_damping_on": Field("intrinsic", "logical", None),
        "radiation_zero_average": Field("intrinsic", "logical", None),
        "radiation_fluctuations_on": Field("intrinsic", "logical", None),
        "conserve_taylor_maps": Field("intrinsic", "logical", None),
        "absolute_time_tracking": Field("intrinsic", "logical", None),
        "absolute_time_ref_shift": Field("intrinsic", "logical", None),
        "convert_to_kinetic_momentum": Field("intrinsic", "logical", None),
        "normalize_twiss": Field("intrinsic", "logical", None),
        "aperture_limit_on": Field("intrinsic", "logical", None),
        "spin_n0_direction_user_set": Field("intrinsic", "logical", None),
        "debug": Field("intrinsic", "logical", None),
    },
    "tao_global_struct": {
        "beam_dead_cutoff": Field("intrinsic", "real", None),
        "lm_opt_deriv_reinit": Field("intrinsic", "real", None),
        "de_lm_step_ratio": Field("intrinsic", "real", None),
        "de_var_to_population_factor": Field("intrinsic", "real", None),
        "lmdif_eps": Field("intrinsic", "real", None),
        "lmdif_negligible_merit": Field("intrinsic", "real", None),
        "svd_cutoff": Field("intrinsic", "real", None),
        "unstable_penalty": Field("intrinsic", "real", None),
        "merit_stop_value": Field("intrinsic", "real", None),
        "dmerit_stop_value": Field("intrinsic", "real", None),
        "random_sigma_cutoff": Field("intrinsic", "real", None),
        "delta_e_chrom": Field("intrinsic", "real", None),
        "max_plot_time": Field("intrinsic", "real", None),
        "default_universe": Field("intrinsic", "integer", None),
        "default_branch": Field("intrinsic", "integer", None),
        "n_opti_cycles": Field("intrinsic", "integer", None),
        "n_opti_loops": Field("intrinsic", "integer", None),
        "n_threads": Field("intrinsic", "integer", None),
        "phase_units": Field("intrinsic", "integer", None),
        "bunch_to_plot": Field("intrinsic", "integer", None),
        "random_seed": Field("intrinsic", "integer", None),
        "n_top10_merit": Field("intrinsic", "integer", None),
        "srdt_gen_n_slices": Field("intrinsic", "integer", None),
        "datum_err_messages_max": Field("intrinsic", "integer", None),
        "srdt_sxt_n_slices": Field("intrinsic", "integer", None),
        "srdt_use_cache": Field("intrinsic", "logical", None),
        "quiet": Field("intrinsic", "character", None, 12),
        "random_engine": Field("intrinsic", "character", None, 16),
        "random_gauss_converter": Field("intrinsic", "character", None, 16),
        "track_type": Field("intrinsic", "character", None, 16),
        "lat_sigma_calc_uses_emit_from": Field("intrinsic", "character", None, 20),
        "prompt_string": Field("intrinsic", "character", None, 40),
        "prompt_color": Field("intrinsic", "character", None, 16),
        "optimizer": Field("intrinsic", "character", None, 16),
        "print_command": Field("intrinsic", "character", None, 40),
        "var_out_file": Field("intrinsic", "character", None, 80),
        "history_file": Field("intrinsic", "character", None, 100),
        "beam_timer_on": Field("intrinsic", "logical", None),
        "box_plots": Field("intrinsic", "logical", None),
        "blank_line_between_commands": Field("intrinsic", "logical", None),
        "cmd_file_abort_on_error": Field("intrinsic", "logical", None),
        "concatenate_maps": Field("intrinsic", "logical", None),
        "derivative_recalc": Field("intrinsic", "logical", None),
        "derivative_uses_design": Field("intrinsic", "logical", None),
        "disable_smooth_line_calc": Field("intrinsic", "logical", None),
        "draw_curve_off_scale_warn": Field("intrinsic", "logical", None),
        "external_plotting": Field("intrinsic", "logical", None),
        "label_lattice_elements": Field("intrinsic", "logical", None),
        "label_keys": Field("intrinsic", "logical", None),
        "lattice_calc_on": Field("intrinsic", "logical", None),
        "only_limit_opt_vars": Field("intrinsic", "logical", None),
        "opt_with_ref": Field("intrinsic", "logical", None),
        "opt_with_base": Field("intrinsic", "logical", None),
        "opt_match_auto_recalc": Field("intrinsic", "logical", None),
        "opti_write_var_file": Field("intrinsic", "logical", None),
        "optimizer_allow_user_abort": Field("intrinsic", "logical", None),
        "optimizer_var_limit_warn": Field("intrinsic", "logical", None),
        "plot_on": Field("intrinsic", "logical", None),
        "rad_int_user_calc_on": Field("intrinsic", "logical", None),
        "rf_on": Field("intrinsic", "logical", None),
        "single_step": Field("intrinsic", "logical", None),
        "stop_on_error": Field("intrinsic", "logical", None),
        "svd_retreat_on_merit_increase": Field("intrinsic", "logical", None),
        "var_limits_on": Field("intrinsic", "logical", None),
        "wait_for_cr_in_single_mode": Field("intrinsic", "logical", None),
        "symbol_import": Field("intrinsic", "logical", None),
        "debug_on": Field("intrinsic", "logical", None),
        "expression_tree_on": Field("intrinsic", "logical", None),
        "verbose_on": Field("intrinsic", "logical", None),
    },
}

# Derived types referenced by the schema but absent from the struct data; paths
# descending into these cannot have their member names or leaf types validated.
MISSING_STRUCTS: tuple[str, ...] = ("old_tao_ele_shape_struct",)
