name: "conda setup"
description: "Prepare a conda environment"
inputs:
  filename:
    description: "Conda environment specification filename"
    required: true
    default: "environment.yml"
  env_name:
    description: "Conda environment name to create"
    required: true
    default: "latform"
  env_var:
    description: "Top level directory environment variable to set"
    required: false
    default: "LATFORM"
runs:
  using: "composite"
  steps:
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: ${{ inputs.env_name }}
        use-mamba: true
        channels: conda-forge
    - name: Set cache date
      shell: bash -l {0}
      run: |
        echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - uses: actions/cache@v3
      with:
        path: ${{ env.CONDA }}/envs
        key: conda-${{ hashFiles(inputs.filename) }}-${{ env.DATE }}
      id: cache
    - name: Update environment
      shell: bash -l {0}
      run: |
        if [ -f "${{ inputs.filename }}" ]; then
          mamba env update -n ${{ inputs.env_name }} -f ${{ inputs.filename }}
        else
          echo "No conda environment file found; skipping. Path: ${{ inputs.filename }}"
        fi
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Setup the environment
      shell: bash -l {0}
      run: |
        # Export as environment variable for convenience
        echo "${{ inputs.env_var }}=${{ github.workspace }}" >> "${GITHUB_ENV}"
        pip install .[test,doc]
